syslocation Finance-Department-Desk-14
syscontact user@netra.local
sysName Host1-Workstation
sysDescr Linux host1 6.2.0-39-generic #40-Ubuntu SMP x86_64 GNU/Linux
sysObjectID .1.3.6.1.4.1.8072.3.2.10

rocommunity public 0.0.0.0/0
rocommunity6 public default

view all included .1
access notConfigGroup "" any noauth exact all none none

