FROM alpine:3.19

RUN apk update && apk add --no-cache \
    net-snmp \
    net-snmp-tools \
    lldpd \
    iproute2 \
    iputils \
    bash \
    curl

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 161/udp

ENTRYPOINT ["/entrypoint.sh"]

